version: 2


models:
  - name: stg_btc
    columns:
      - name: HASH_KEY
        tests:
          - unique
          - not_null

  - name: stg_btc_outputs
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_btc_outputs_py')

  - name: whale_alerts
    latest_version: 1
    config:
      contract:
        enforced: true
    columns:
      - name: INVOCATION_ID
        data_type: string
      - name: output_address
        data_type: string
        data_tests:
          - assert_valid_btc_address
      - name: total_sent
        data_type: float
      - name: tx_count
        data_type: int
      - name: total_sent_usd
        data_type: float

    versions:
      - v: 1
        # Matches what's above
      - v: 2
        # Breaking change: removed total_sent_usd
        columns:
          - include: all
            exclude: [total_sent_usd]


